const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const CHANGE_TODO_STATE = "CHANGE_TODO_STATE";
const SET_GROUP_BY = "SET_GROUP_BY";
const SET_SELECTED_TAB = "SET_SELECTED_TAB";
const SET_MODAL_TITLE = "SET_MODAL_TITLE";
const SORT_BY_CREATEDAT = "SORT_BY_CREATEDAT";
const SORT_BY_PRIORITY = "SORT_BY_PRIORITY";
const SORT_BY_DUE_DATE = "SORT_BY_DUE_DATE";
const SORT_BY_SUMMARY = "SORT_BY_SUMMARY";
const SEARCH = "SEARCH";

const TodoActions = {
  ADD_TODO,
  DELETE_TODO,
  UPDATE_TODO,
  CHANGE_TODO_STATE,
  SET_GROUP_BY,
  SET_SELECTED_TAB,
  SET_MODAL_TITLE,
  SORT_BY_CREATEDAT,
  SORT_BY_PRIORITY,
  SORT_BY_DUE_DATE,
  SORT_BY_SUMMARY,
  SEARCH,
};

export default TodoActions;
